### ISSUE TITLE
TeamSpeak3QueryApi.Net.QueryException: An error occurred during the query.

### ISSUE THREAD

**Issue by JunTVDE** [PourrezJ/RAGEMP_GTA5_TSVoice#1]
```
TeamSpeak3QueryApi.Net.QueryException: An error occurred during the query.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TeamSpeak3QueryApi.Net.QueryClient.<Send>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RAGEMP_TsVoice.Teamspeak.<CheckSpeakingClients>d__31.MoveNext()
commercialcardealership ON business.id = commercialcardealership.id' ends with: 0.69s
TeamSpeak3QueryApi.Net.QueryException: An error occurred during the query.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TeamSpeak3QueryApi.Net.QueryClient.<Send>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TeamSpeak3QueryApi.Net.Specialized.TeamSpeakClient.<FindChannel>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RAGEMP_TsVoice.Teamspeak.<CheckSpeakingClients>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RAGEMP_TsVoice.Teamspeak.<<OnResourceStart>b__27_0>d.MoveNext()
Teamspeak Wrapper Initialised!
```

We are getting this error when the script starts. Can you help us?
Also we get renamed the whole time and get muted without moving while speaking.

**Comment by JunTVDE** [comment]
The error could be fixed, but the renaming and muting is still happening.

**Comment by JunTVDE** [comment]
Sorry, none of the described errors are related to your script. Im so sorry.
The script is working great, thank you so much for sharing!
